NilFoundation/zkLLVM

cmake/CircuitCompile.cmake
=> Add crypto3 include directories to circuit compilation

examples/arithmetics.cpp
=> Support call instruction handling in assinger

.gitmodules, README.md
New submodules were added, fixing paths for them.
=> Use protocol-independent paths to submodules

.gitignore, bin/transpiler/src/main.cpp
Transpiler dependencies updated to support batched commitments.
Transpiler interface is slightly updated.
Updated submodule assigned to fix a memory management bug.
Closes #57
=> Transpiler dependencies update

examples/CMakeLists.txt
=> Enable disabled examples

.github/workflows/build_macos.yml, README.md, cmake/CheckAVX.cmake
=> dev: add CI on macOS

.github/workflows/build_linux.yml, .gitmodules, CMakeLists.txt
=> Add rslang submodule

.gitmodules, CMakeLists.txt
Dependency from Crypto3 changed from "by submodules" to dependency from crypto3 only. It is fixed on the version with the new math::expression.
=> Crypto3 submodule update

examples/CMakeLists.txt, examples/strlen.cpp, examples/strlen.inp
=> Add example with string public input

gitbook-docs/tutorials/01-hashes.md, gitbook-docs/tutorials/02-eddsa.md, gitbook-docs/tutorials/03-merkle-tree.md, gitbook-docs/tutorials/04-zkbridge.md
Proofread the zkLLVM tutorials
* Fixed some issues with grammar and word choice.
* Formatted the code to fit in the code blocks on GitBook.
=> docs: Proofread zkLLVM tutorials

bin/transpiler/src/main.cpp
Now transpiler can be called with an additional mode to only generate circuit parameters without proving phase:
`transpiler  -m gen-circuit-params -t template.tbl -c template.crct -o template`
Closes #162
=> gen-circuit-params option added to the transpiler

.github/workflows/build_linux.yml, .github/workflows/build_macos.yml, .github/workflows/release_linux.yml, bin/assigner/src/main.cpp
=> Integrate logging of assigner

bin/transpiler/src/main.cpp
Adds `--skip-verfication` option to the transpiler + some (more) verbose output to keep track of what's happening.
=> Added option to skip proof verification

examples/cpp/CMakeLists.txt
=> Rust compilation fixed

CMakeLists.txt, bin/assigner/CMakeLists.txt, bin/assigner/src/main.cpp, bin/transpiler/CMakeLists.txt, bin/transpiler/src/main.cpp
Fix for issue https://github.com/NilFoundation/zkllvm/issues/140
=> Print version for assigner and transpiler binaries

CMakeLists.txt, README.md, rslang-installer.py
After merging this PR we should make new release
=> Switch to Rust nightly channel

bin/transpiler/src/main.cpp
This PR adds optimizations done on transpiler side, updates crypto3-zk and transpiler submodules.
=> 309 optimize evm code cp

CMakeLists.txt, cmake/CircuitCompile.cmake, examples/cpp/CMakeLists.txt, examples/cpp/balances_tree.cpp, tests/cpp/CMakeLists.txt
=> Simplify format handling, generate error for unknown attrs

.github/workflows/build_linux.yml, .github/workflows/build_macos.yml, .github/workflows/release_linux.yml, README.md, bin/assigner/src/main.cpp
- Spdlog substituted by Boost log
- New assigner option added. Log level can now be changed with -l option.
=> Boost log added instead of spdlog

tests/cpp/CMakeLists.txt
=> Fix constant GetElementPtr for debug

bin/transpiler/src/main.cpp
Update transpiler lib and crypto3, fix transpiler main after changes in ZK.
=> Update transpiler lib and crypto3, fix transpiler main after changes in ZK.

bin/assigner/src/main.cpp, bin/transpiler/src/main.cpp
=> Print to binary file [SyncWith:zkllvm#464]

bin/assigner/src/main.cpp
- print circuit and assignment table only for `target_prover`
- **assigner:** support `generate_empty_assignment` for fill assignment table only by components associated with `target_prover`
- **blueprint:** implement `is_satisfied` only for `target_prover`
- **cirtifier:** fix set pragma `zk_multi_provers` for comples sub STMT like `for`, `if`, ...
Closes #406
=> Skip components

CMakeLists.txt, bin/CMakeLists.txt, bin/assigner/CMakeLists.txt, bin/assigner/src/main.cpp, bin/recursive_gen/CMakeLists.txt, bin/recursive_gen/src/main.cpp, bin/transpiler/CMakeLists.txt, bin/transpiler/src/main.cpp
Closes https://github.com/NilFoundation/zkLLVM/issues/519
=> 519 Handle llvm undefined poison value

bin/assigner/src/main.cpp
=> Update assigner interfaces

.github/workflows/build_linux.yml, bin/assigner/src/main.cpp, examples/CMakeLists.txt, examples/rust/CMakeLists.txt
=> Generate input column for verifier
